server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/menu_service
    username: menu_user
    password: menu_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    minimumIdle: 5
    maximumPoolSize: 10
    autoCommit: true
  jpa:
    hibernate:
      ddl-auto: none  # using SQL scripts for schema
    show-sql: false   # Disable SQL logging in Docker environment
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: redis
      port: 6379
      password:  # leave empty if no password is set
      database: 0
      timeout: 60000

documentation:
  openapi:
    title: "Menu Service API"
    description: "API documentation for Menu Service"
    version: "1.0"
    contact-name: "Development Team"
    contact-email: "dev@example.com"
    group:
      name: "public"
      paths-to-match:
        - "/api/**"

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      base-path: /api/v1
      exposure:
        include: info, health, metrics
